### PR TITLE
Update to 3.0.1-OS1

### PR DESCRIPTION
**Pull request by hugobgranja**
## Description

Updated from version 2.2.1 to 3.0.1-OS1 by merging with the cordova repository.

## Context

https://trello.com/c/qmg4CxW9/3-contacts-plugin

## Type of changes

- [x] Feature (change which adds functionality)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to new feature)
- [x] Fix (change which fixes an issue)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to fix)
- [ ] Performance (change which improves performance)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to performance improvement)
- [ ] Refactor (non-breaking change that is neither feature, fix nor performance)
- [ ] Style (non-breaking change that only affects formatting and/or white-space)

## Components affected
- [x] Android platform
- [x] iOS platform
- [x] JavaScript
- [ ] OutSystems

## Checklist

- [ ] Pull request title follows the format `RNMT-XXXX <title>`
- [ ] Tests have been created
- [x] Code follows code style of this project
- [x] CHANGELOG.md file is correctly updated
- [ ] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

### CODE REVIEW

**Review by bgracio — APPROVED** [review]

**Review by EiyuuZack — APPROVED** [review]
No conflicts with our customisations. Looks good to me.

**Comment by EiyuuZack** [comment]
@luissilvaos can you check why the tests failed please?

**Comment by luissilvaos** [comment]
@EiyuuZack the tests failed because the PR came from outside our repository 😞 We'll need to tweak  the pipeline for this use case.

**Comment by EiyuuZack** [comment]
@luissilvaos Given there were no conflicts with our customisations and assuming the plugin built successfully before opening this pull-request I am comfortable with merging.

Your call.

**Comment by EiyuuZack** [comment]
Overriding checks because testing infrastructure does not yet accommodate pull requests from external repositories.

**Pull request merged**
